create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.strava_tokens (
  id bigint generated by default as identity primary key,
  athlete_id bigint not null unique,
  access_token text not null,
  refresh_token text not null,
  expires_at timestamptz not null,
  token_type text,
  scope text[] default '{}',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.athletes (
  athlete_id bigint primary key,
  username text,
  firstname text,
  lastname text,
  bio text,
  city text,
  state text,
  country text,
  sex text,
  profile text,
  profile_medium text,
  follower_count integer,
  friend_count integer,
  weight numeric,
  raw_stats jsonb,
  last_synced_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.activities (
  id bigint primary key,
  athlete_id bigint not null references public.athletes (athlete_id) on delete cascade,
  name text not null,
  type text not null,
  sport_type text not null,
  start_date timestamptz not null,
  timezone text,
  distance_meters numeric not null default 0,
  moving_time_seconds integer not null default 0,
  elapsed_time_seconds integer not null default 0,
  total_elevation_gain numeric not null default 0,
  average_speed numeric,
  max_speed numeric,
  average_heartrate numeric,
  max_heartrate numeric,
  kilojoules numeric,
  achievement_count integer default 0,
  kudos_count integer default 0,
  comment_count integer default 0,
  trainer boolean not null default false,
  commute boolean not null default false,
  manual boolean not null default false,
  private boolean not null default false,
  flagged boolean not null default false,
  start_latlng jsonb,
  end_latlng jsonb,
  map_summary_polyline text,
  map_resource_state integer,
  raw_payload jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.activity_streams (
  activity_id bigint primary key references public.activities (id) on delete cascade,
  latlng jsonb,
  distance jsonb,
  altitude jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.aggregated_stats (
  id uuid primary key default gen_random_uuid(),
  athlete_id bigint not null references public.athletes (athlete_id) on delete cascade,
  bucket_granularity text not null check (bucket_granularity in ('all', 'week', 'month', 'year')),
  bucket_date date not null,
  activity_type text not null default 'all',
  activity_count integer not null default 0,
  total_distance_meters numeric not null default 0,
  total_elevation_gain numeric not null default 0,
  total_moving_time_seconds integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (athlete_id, bucket_granularity, bucket_date, activity_type)
);

create table if not exists public.sync_logs (
  id uuid primary key default gen_random_uuid(),
  athlete_id bigint references public.athletes (athlete_id) on delete set null,
  sync_type text not null,
  status text not null check (status in ('running', 'success', 'error')),
  activities_processed integer,
  error_message text,
  metadata jsonb,
  started_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_activities_athlete_start_date on public.activities (athlete_id, start_date desc);
create index if not exists idx_activities_sport_type_start_date on public.activities (sport_type, start_date desc);
create index if not exists idx_aggregated_stats_lookup on public.aggregated_stats (athlete_id, bucket_granularity, bucket_date desc);
create index if not exists idx_sync_logs_started_at on public.sync_logs (started_at desc);
create index if not exists idx_sync_logs_status on public.sync_logs (status);

drop trigger if exists set_updated_at_on_strava_tokens on public.strava_tokens;
create trigger set_updated_at_on_strava_tokens
before update on public.strava_tokens
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_on_athletes on public.athletes;
create trigger set_updated_at_on_athletes
before update on public.athletes
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_on_activities on public.activities;
create trigger set_updated_at_on_activities
before update on public.activities
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_on_activity_streams on public.activity_streams;
create trigger set_updated_at_on_activity_streams
before update on public.activity_streams
for each row execute procedure public.set_updated_at();

drop trigger if exists set_updated_at_on_aggregated_stats on public.aggregated_stats;
create trigger set_updated_at_on_aggregated_stats
before update on public.aggregated_stats
for each row execute procedure public.set_updated_at();

create or replace function public.refresh_aggregated_stats(p_athlete_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.aggregated_stats where athlete_id = p_athlete_id;

  insert into public.aggregated_stats (
    athlete_id,
    bucket_granularity,
    bucket_date,
    activity_type,
    activity_count,
    total_distance_meters,
    total_elevation_gain,
    total_moving_time_seconds
  )
  with base as (
    select
      athlete_id,
      sport_type,
      start_date::date as activity_date,
      distance_meters,
      total_elevation_gain,
      moving_time_seconds
    from public.activities
    where athlete_id = p_athlete_id
  ),
  rollups as (
    select athlete_id, 'all'::text as bucket_granularity, current_date as bucket_date, 'all'::text as activity_type,
      count(*)::integer as activity_count,
      coalesce(sum(distance_meters), 0)::numeric as total_distance_meters,
      coalesce(sum(total_elevation_gain), 0)::numeric as total_elevation_gain,
      coalesce(sum(moving_time_seconds), 0)::integer as total_moving_time_seconds
    from base
    group by athlete_id

    union all

    select athlete_id, 'all', current_date, sport_type,
      count(*)::integer,
      coalesce(sum(distance_meters), 0)::numeric,
      coalesce(sum(total_elevation_gain), 0)::numeric,
      coalesce(sum(moving_time_seconds), 0)::integer
    from base
    group by athlete_id, sport_type

    union all

    select athlete_id, 'week', date_trunc('week', activity_date)::date, 'all',
      count(*)::integer,
      coalesce(sum(distance_meters), 0)::numeric,
      coalesce(sum(total_elevation_gain), 0)::numeric,
      coalesce(sum(moving_time_seconds), 0)::integer
    from base
    group by athlete_id, date_trunc('week', activity_date)::date

    union all

    select athlete_id, 'month', date_trunc('month', activity_date)::date, 'all',
      count(*)::integer,
      coalesce(sum(distance_meters), 0)::numeric,
      coalesce(sum(total_elevation_gain), 0)::numeric,
      coalesce(sum(moving_time_seconds), 0)::integer
    from base
    group by athlete_id, date_trunc('month', activity_date)::date

    union all

    select athlete_id, 'year', date_trunc('year', activity_date)::date, 'all',
      count(*)::integer,
      coalesce(sum(distance_meters), 0)::numeric,
      coalesce(sum(total_elevation_gain), 0)::numeric,
      coalesce(sum(moving_time_seconds), 0)::integer
    from base
    group by athlete_id, date_trunc('year', activity_date)::date
  )
  select
    athlete_id,
    bucket_granularity,
    bucket_date,
    activity_type,
    activity_count,
    total_distance_meters,
    total_elevation_gain,
    total_moving_time_seconds
  from rollups;
end;
$$;

create or replace view public.public_sync_status
with (security_invoker = true)
as
select distinct on (athlete_id)
  athlete_id,
  status,
  completed_at,
  activities_processed
from public.sync_logs
where athlete_id is not null
order by athlete_id, coalesce(completed_at, started_at) desc;

create or replace view public.dashboard_overview
with (security_invoker = true)
as
with totals as (
  select
    athlete_id,
    count(*)::integer as activity_count,
    count(*) filter (where sport_type = 'Ride')::integer as ride_count,
    count(*) filter (where sport_type = 'Run')::integer as run_count,
    count(*) filter (where sport_type not in ('Ride', 'Run'))::integer as other_count,
    coalesce(sum(distance_meters), 0)::numeric as total_distance_meters,
    coalesce(sum(total_elevation_gain), 0)::numeric as total_elevation_gain,
    coalesce(sum(moving_time_seconds), 0)::integer as total_moving_time_seconds
  from public.activities
  group by athlete_id
)
select
  a.athlete_id,
  trim(concat(coalesce(a.firstname, ''), ' ', coalesce(a.lastname, ''))) as display_name,
  a.username,
  a.city,
  a.state,
  a.country,
  a.profile,
  a.profile_medium,
  t.activity_count,
  t.ride_count,
  t.run_count,
  t.other_count,
  t.total_distance_meters,
  t.total_elevation_gain,
  t.total_moving_time_seconds,
  s.completed_at as last_synced_at,
  s.status as last_sync_status
from public.athletes a
left join totals t on t.athlete_id = a.athlete_id
left join public.public_sync_status s on s.athlete_id = a.athlete_id;

alter table public.strava_tokens enable row level security;
alter table public.athletes enable row level security;
alter table public.activities enable row level security;
alter table public.activity_streams enable row level security;
alter table public.aggregated_stats enable row level security;
alter table public.sync_logs enable row level security;

create policy "Public read athletes"
on public.athletes
for select
to anon, authenticated
using (true);

create policy "Public read activities"
on public.activities
for select
to anon, authenticated
using (true);

create policy "Public read activity streams"
on public.activity_streams
for select
to anon, authenticated
using (true);

create policy "Public read aggregated stats"
on public.aggregated_stats
for select
to anon, authenticated
using (true);

grant select on public.athletes to anon, authenticated;
grant select on public.activities to anon, authenticated;
grant select on public.activity_streams to anon, authenticated;
grant select on public.aggregated_stats to anon, authenticated;
grant select on public.dashboard_overview to anon, authenticated;
grant select on public.public_sync_status to anon, authenticated;
